default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: bluprint
  password: 123

development:
  <<: *default
  database: bluprint_development

test:
  <<: *default
  database: bluprint_test

production:
  <<: *default
  database: bluprint_production
  username: bluprint
  password: <%= ENV['BLUPRINT_DATABASE_PASSWORD'] %>
